### ISSUE TITLE
Names for Weston and Kiosk Demo Apps

### ISSUE THREAD

**Issue by danilosiviana** [torizon/evaluation-apps#3]
We from Toradex Technical Marketing Team created the docker-compose files for Weston and Kiosk. They should work for all the modules, as indicated by the name. We would like help defining the names for the app so we can submit a pull request.

![image](https://github.com/torizon/evaluation-apps/assets/145570653/e6c1774d-c33c-406f-8eed-1465085ae48e)

**Comment by leograba** [comment]
Here's my 5 cent.

Today the repo structure is:

```
leonardo@leonardov-nb:evaluation-apps$ tree
.
├── LICENSE.md
├── node-red
│   ├── app.json
│   ├── docker-compose.yml
│   ├── icon.png
│   └── README.md
├── README.md
└── weston
    ├── app.json
    ├── docker-compose.yml
    ├── icon.png
    └── README.md

2 directories, 10 files
```

First point, which is solved: each folder is an app. This means you will have to update the existing `weston` and add a new directory `kiosk`.

----

Second point, which is open: how to have multiple Compose files for a single app. I can think of some options:

Option 1 - app with a single directory, multiple compose for different platforms:

```
leonardo@leonardov-nb:evaluation-apps$ tree
.
├── LICENSE.md
├── README.md
└── weston
    ├── docker-compose-<platform1>.yml
    ├── docker-compose-<platform2>.yml
     ...
    ├── docker-compose-<platformN>.yml

2 directories, 10 files
```

Option 2 - app with one directory per platform, one compose per platform:

```
leonardo@leonardov-nb:evaluation-apps$ tree
.
├── LICENSE.md
├── README.md
└── weston-<platform1>
    ├── docker-compose.yml
└── weston-<platformN>
    ├── docker-compose.yml

2 directories, 10 files
```

Option 3 - one directory per platform, one directory per app with a single compose file:

```
leonardo@leonardov-nb:evaluation-apps$ tree
.
├── LICENSE.md
├── README.md
└── <platform1>
    ├── app1
        ├── docker-compose.yml
    ├── appN
        ├── docker-compose.yml
└── <platformN>
    ├── app1
        ├── docker-compose.yml
    ├── appN
        ├── docker-compose.yml
```

There may be other options. I think we should aim for keeping metadata de-duplicated, which is why I would prefer Option 1. But I think it is also important to get feedback from the devs on Torizon OS and the Cloud teams.

----

Another important factor to define early to avoid renamings in the future, is the platform names. Your example has:

- am62
- apalis-colibri-imx6
- colibri-imx7-imx6ull
- vivante

My suggestion is to follow 1 to 1 the same platform schema adopted by the TCCP (packages and containers) team. But again, I'd like to hear from them.

@leonheldattoradex and @tkfu, you'd be much better at providing feedback about this than me. And as a PO, I'm even stepping a bit out of my role with the above, but I can't help as I'm excited about the topic, and also concerned with having a solid base to make it scalable.

**Comment by danilosiviana** [comment]
Just throwing out an additional idea, how about maintaining different platforms as different package versions?
![image](https://github.com/torizon/evaluation-apps/assets/145570653/ef049bbf-ad07-4e57-a316-e3b1c40a877b)

**Comment by leograba** [comment]
Your idea is another good point to discuss. It could be independent, as it's more about publishing on the Platform than directory structure IMO.

**Comment by danilosiviana** [comment]
You are right. Should I open a discussion in another channel as it does not reflect in this repo?

**Comment by lucas-tdx** [comment]
Just my two cents, as marketing input:

> Second point, which is open: how to have multiple Compose files for a single app.

I also like @leograba's Option 1 for repo organization. I believe we would need to update the CI workflows to additionally sign and upload each docker-compose file

> Just throwing out an additional idea, how about maintaining different platforms as different package versions?

I would be against it, because we can't deeplink to a specific package version, only to the package name. This would break the guardrails we have in other places - torizon.io, developer.toradex.com - to make sure the user deploys the correct package for their hardware (using deeplinks directly to the package they should deploy).

**Comment by danilosiviana** [comment]
You have a nice point, Lucas! Thanks for the insight.

**Comment by lucas-tdx** [comment]
Hmm, I see the issue. Maybe we can keep just one `app.json` file by structuring the CI so that the published packages have a naming convention. e.g. for package named `weston` and the `docker-compose.xxxxx.yml` file, the published package name on the delegation would be `weston-xxxxx`. This would assume all variants would share the same package version, from the json

**Comment by leograba** [comment]
This pending decision is blocking 3 MRs.

I'd be ok, as of today, following the structure pattern used by @otaviocp on his MRs:

- Each app in a single directory
- Multiple compose for different SoMs, defined as `docker-compose-<som>.yml`

@leonheldattoradex please take over the final decision.

**Comment by danilosiviana** [comment]
Hi everyone. After talking with Jon, he agreed to extend the app.json to support the structure used by Otavio. He also agreed to work on supporting it in the pipeline. So I strongly suggest going forward as proposed in the MR.

**Comment by leonheldattoradex** [comment]
I'm still not fully convinced we should do this instead of parse and get by platform (`am62`, `imx8`, `imx95`) on the server side of Torizon Cloud. You can see from the MRs that this generates *a lot* of repetition and the customer has to know (for no technical reason whatsoever) which board + SoC he is using.

@danilosiviana have you spoken to Jon in regards to this? Is there a strong technical reason why we're doing the repetition and not matching it server-side on Torizon Cloud?

**Comment by danilosiviana** [comment]
I get your point. 
Changing the pipeline is somewhat trivial and decoupled from the Cloud maintenance/product management cycle. We can do this ASAP.

Changing the Cloud requires proper investigation, thinking, and a product management cycle. 
I think we can't afford that before get a minimal working demo gallery.
 
We discussed this in the past and the topic didn't reach the backlog.

**Comment by tkfu** [comment]
> Is there a strong technical reason why we're doing the repetition and not matching it server-side on Torizon Cloud?

"Matching it server side" is a short phrase that masks a lot of complexity. Remember, a package in Uptane is identified by its hash. If the user says "I want to install package `foo-1.0.1` on device `bar`", we always send the exact same file--whatever the signed metadata in the repository says `foo-1.0.1` is. You can't have two different packages in one repository that have the exact same identifier but two different hashes.

We also don't _really_ get information about what platform the device is running, with respect to the application component: every application component has the same hardware_id (`docker-compose`). Components (or ECUs or Subsystems, depending on which nomenclature you prefer) are pretty independent in Uptane: a component might represent the application stack on a module, but it also might be a completely separate system. For example, imagine a system where you have a primary that's an apalis-imx8 running Torizon OS minimal (no application component), and a secondary that's a colibri-imx6ull running Torizon OS with an application stack. Our components are `apalis-imx8`, `colibri-imx6ull`, and `docker-compose`. How should Torizon Cloud know which architecture the `docker-compose` component needs?

Now, of course we could have decided to give the application component a different hardware_id depending on what platform it's running on (`docker-compose-imx8`, `docker-compose-am62`, etc.). But the decision not to do that was made long ago, and I don't think it's changing any time soon. I also still believe that was the correct choice; after all, the vast majority of docker-compose files aren't platform specific, and in any production use case we can expect the end user to know the configuration of their systems.

**Comment by leonheldattoradex** [comment]
I think I now properly understand the technical limitations and the whys and hows after hearing from TM/PM/OTA/TOR....

Striking the mallet on this decision hoping that...

> I do like @danilosiviana's proposal

... something like that gets merged and a POC shows up here so we don't need to maintain multiple copies of the same file in the repo.

I'll start reviewing and merging the MRs as soon as possible.

Thanks everyone.
